### ISSUE TITLE
a few optimizations - delete a line, hide visibility during updates

### ISSUE THREAD

**Issue by satra** [maartenbreddels/ipyvolume#71]
i'm using a `plot` command to plot a set of lines together with interact.

1. i see that each scatter object is being added to figure. how do i delete a particular object from the figure?
2. how do i pause a visual update as i draw lines with interact? the opposite of p3.show()?

**Comment by maartenbreddels** [comment]
Could you share your code, or a reduced version of it?
Maybe instead of adding and deleting a line, you can modify the x,y,z values of the Scatter object?

> 1. i see that each scatter object is being added to figure. how do i delete a particular object from the figure?

Figure has [a scatters](https://github.com/maartenbreddels/ipyvolume/blob/771b76987e03800ddafa558f0518546d85b8094b/ipyvolume/widgets.py#L113) trait, which is a list of all scatter object, you can modify this as you want.
Be be aware, changing made to this list will not be detected by the traitlets library, the best way to do it, is make a copy, remove the element and assign it to the figure object.

> 2. how do i pause a visual update as i draw lines with interact? the opposite of p3.show()?

You mean, you want to add many lines, but you do not want to update the plot after each addition? Instead you'd want to say add 10 lines, and after that do 1 update?

**Comment by satra** [comment]
@maartenbreddels - the code is here:

https://github.com/satra/niwidgets/blob/aca33f1f11372a4e57d7925a002996fd66862899/niwidgets/streamlines.py#L108

the main problem is the for loop which would ideally be over 50k - 100k lines, but currently i'm reducing by a factor of 50-100 to perform additions/removals. lines have different lengths, so i precompute them and use this function to hide/show lines:

https://github.com/satra/niwidgets/blob/aca33f1f11372a4e57d7925a002996fd66862899/niwidgets/streamlines.py#L123

being able to do both of the above operations in bulk would be nice.

> You mean, you want to add many lines, but you do not want to update the plot after each addition? Instead you'd want to say add 10 lines, and after that do 1 update?

yes.

**Comment by maartenbreddels** [comment]
Can you try if this speeds it up?
```python
with fig.hold_sync():
  # add all lines
# now the figure's traits will be synced (the line of scatters will be send to the frontend in one go)
```

(see https://github.com/jupyter-widgets/ipywidgets/blob/24f3312897f2694f10fddd207206af0aae10ecce/ipywidgets/widgets/widget.py#L630 )

**Comment by satra** [comment]
thanks for this - it definitely helps speeding up the initial plot. but i still can't get to much more than a 1000 lines. notebook appears to freeze up. if you would like to try here is the notebook:

https://www.dropbox.com/s/oukfh9agca5k9im/streamlines.ipynb?dl=0

here is the niwidgets branch:
https://github.com/satra/niwidgets/tree/enh/streamlines

and here is the trk file:
https://www.dropbox.com/s/dbexuhk7fsawvox/streamlines.trk?dl=0

you'll need nibabel to read and the parameter to change is `skip`.

**Comment by satra** [comment]
thanks @maartenbreddels - this is now fixed.

**Comment by nvaytet** [comment]
> Could you share your code, or a reduced version of it?
> Maybe instead of adding and deleting a line, you can modify the x,y,z values of the Scatter object?
> 
> > 1. i see that each scatter object is being added to figure. how do i delete a particular object from the figure?
> 
> Figure has [a scatters](https://github.com/maartenbreddels/ipyvolume/blob/771b76987e03800ddafa558f0518546d85b8094b/ipyvolume/widgets.py#L113) trait, which is a list of all scatter object, you can modify this as you want.
> Be be aware, changing made to this list will not be detected by the traitlets library, the best way to do it, is make a copy, remove the element and assign it to the figure object.
> 
> > 1. how do i pause a visual update as i draw lines with interact? the opposite of p3.show()?
> 
> You mean, you want to add many lines, but you do not want to update the plot after each addition? Instead you'd want to say add 10 lines, and after that do 1 update?

@maartenbreddels when setting `fig.scatters = []` to clear the scatter and plot new ones, could you tell me how I can then update the figure that is already showing rather than having to call `ipv.show()` again to show a new instance of the updated figure?
Thanks!

**Comment by nvaytet** [comment]
e.g.
```Py
import ipyvolume as ipv
import numpy as np
a = np.arange(-5, 5)
U, V = np.meshgrid(a, a)
X = U
Y = V
Z = X*Y**2

fig = ipv.figure()
surf = ipv.plot_surface(X, Z, Y, color="orange")
wfrm = ipv.plot_wireframe(X, Z, Y, color="red")
ipv.gcc()
fig.meshes = []
surf = ipv.plot_surface(X, np.ones_like(X), Y, color="blue")
```
will still show both surfaces
![Screenshot at 2019-12-05 00-31-44](https://user-images.githubusercontent.com/39047984/70190615-a5581300-16f6-11ea-9a0b-182cf8b29139.png)
but if i call `ipv.gcc()` again, then the orange surface has disappeared
![Screenshot at 2019-12-05 00-32-27](https://user-images.githubusercontent.com/39047984/70190650-c3257800-16f6-11ea-9645-e26bc3539be5.png)

**Comment by nvaytet** [comment]
I know I could set the orange surface to `visible=False` but i may have to change the surface many times, thus adding a new one every time, potentially wasting a lot of memory.
